# permissions for end users to view namespaceclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceclaim-viewer-role
rules:
- apiGroups:
  - claim.tmax.io
  resources:
  - namespaceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - claim.tmax.io
  resources:
  - namespaceclaims/status
  verbs:
  - get
